# Generated by Django 5.0.3 on 2024-04-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0004_transactions_credit_user_transactions_debit_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="transaction_date",
            field=models.DateField(),
        ),
    ]
