# Generated by Django 5.0.3 on 2024-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
