# Generated by Django 5.0.3 on 2024-04-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0006_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "phone",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
