# Generated by Django 5.0.3 on 2024-04-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
